# Generated by Django 5.1.4 on 2024-12-23 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Performance', '0002_performancedata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerformanceData',
        ),
    ]
